# Generated by Django 5.0.4 on 2024-05-01 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_candidate_biography_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.specialization'),
        ),
    ]
