# Generated by Django 5.0.4 on 2024-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='test_passed',
            field=models.BooleanField(default=False),
        ),
    ]
